#aws
cloud:
  aws:
    credentials:
      secret-key: ${AWS_SECRET_KEY}
      access-key: ${AWS_ACCESS_KEY}
    s3:
      bucket: tonemate
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
