server:
  servlet:
    contextPath: /
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 5000
spring:
  redis:
    host: 52.78.139.142
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  profiles:
    include: oauth, aws
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: 1234
      username: tonemate
    url: jdbc:mysql://52.78.139.142:3305/tonemate


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
springfox:
  documentation:
    swagger:
      v2:
        enabled: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error