version: '3.3'
services:

  spring:
    build: ./back-end
    container_name: spring
    ports:
      - 5001:5000

  flask:
    container_name: flask
    build: ./AI
    environment:
      - FLASK_ROOT=${FLASK_ROOT}
      - FLASK_FEATURES=${FLASK_FEATURES}
      - FLASK_TARGET_EPOCH=${FLASK_TARGET_EPOCH}
      - FLASK_PORT=${FLASK_PORT} #기본 5000
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}

  nextdev:
    container_name: front-next
    build:
      context: ./front-end/tonemate
      dockerfile: docker/development/Dockerfile
    ports:
      - '3001:3000'