version: '3.3'
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports : 
      - '8100:8080'
    user: root
    volumes:
      - ./jenkins/home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - ${DATA_PATH}:/var/DATA
    networks:
      - core

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - core


  mysql:
    image: mysql
    container_name: mysql
    environment:
      - TZ = Asia/Seoul
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul   # 시간대 설정
    volumes:
      - ./mysql/mysql-init-files/:/docker-entrypoint-initdb.d/
      - ./mysql/res/data/:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
    ports:
      - 3305:3306
    networks:
      - core

networks:
  core:
    driver: bridge
